sudo: required
services: docker
language: generic

script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo
    - chmod +x cyber-dojo
    - my_url=https://github.com/cyber-dojo/start-points-exercises.git
    - sudo ./cyber-dojo start-point create exercises --git=${my_url}
    - sudo ./cyber-dojo start-point ls
    - sudo ./cyber-dojo start-point ls | grep exercises
